"""One-time module setup: install deps and update the agent's system-prompt doc.

Run at container startup from each agent's entrypoint.sh.  The agent passes
its modules directory and the path to its system-prompt file
(``AGENTS.md`` for Codex/Gemini, ``CLAUDE.md`` for Claude, etc.).
"""

from __future__ import annotations

import argparse
import logging
import os
import subprocess
import sys
from pathlib import Path

from .module_loader import discover_modules, generate_modules_doc

log = logging.getLogger(__name__)

BEGIN_MARKER = "<!-- MODULES:BEGIN -->"
END_MARKER = "<!-- MODULES:END -->"


def run_setup_scripts(modules_dir: str) -> None:
    """Run each module's setup.sh if present (for cloning vendored repos, etc.)."""
    for entry in sorted(Path(modules_dir).iterdir()):
        setup = entry / "setup.sh"
        if setup.exists():
            log.info("Running setup.sh for module %s", entry.name)
            setup.chmod(setup.stat().st_mode | 0o111)
            subprocess.run(["bash", str(setup)], check=True, cwd=str(entry))


def install_requirements(modules_dir: str) -> None:
    """Install requirements.txt for each module that has one."""
    for entry in sorted(Path(modules_dir).iterdir()):
        req = entry / "requirements.txt"
        if req.exists():
            log.info("Installing deps for module %s", entry.name)
            subprocess.run(
                [
                    sys.executable, "-m", "pip", "install",
                    "--break-system-packages", "-q", "-r", str(req),
                ],
                check=True,
            )


def update_agents_md(doc: str, agents_md_path: str) -> None:
    """Replace content between MODULES markers in the agent's system-prompt file."""
    if not os.path.exists(agents_md_path):
        log.warning("System-prompt file not found at %s", agents_md_path)
        return

    with open(agents_md_path) as f:
        content = f.read()

    begin = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    if begin == -1 or end == -1:
        log.warning("Module markers not found in %s — skipping update", agents_md_path)
        return

    replacement = (
        f"{BEGIN_MARKER}\n"
        "<!-- Auto-generated by superpos_agent_core.module_setup — do not edit manually -->\n\n"
        f"{doc}\n"
        f"{END_MARKER}"
    )
    new_content = content[:begin] + replacement + content[end + len(END_MARKER):]

    with open(agents_md_path, "w") as f:
        f.write(new_content)

    log.info("Updated %s with module documentation", agents_md_path)


def run_setup(modules_dir: str, agents_md_path: str) -> None:
    """Discover modules, run setup scripts, install deps, update system prompt."""
    if not os.path.isdir(modules_dir):
        log.info("No modules directory at %s — skipping module setup", modules_dir)
        return

    modules = discover_modules(modules_dir)
    log.info("Discovered %d module(s): %s", len(modules), [m.name for m in modules])

    run_setup_scripts(modules_dir)
    install_requirements(modules_dir)

    doc = generate_modules_doc(modules)
    update_agents_md(doc, agents_md_path)


def main() -> None:
    """CLI entry point invoked from entrypoint.sh."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    parser = argparse.ArgumentParser(description="Slim-agent module setup")
    parser.add_argument(
        "--modules-dir", required=True,
        help="Path to the agent's modules directory (e.g. /workspace/.gemini/modules)",
    )
    parser.add_argument(
        "--agents-md", required=True,
        help="Path to the agent's system-prompt file (e.g. /workspace/AGENTS.md)",
    )
    args = parser.parse_args()
    run_setup(args.modules_dir, args.agents_md)


if __name__ == "__main__":
    main()
