"""One-time module setup: install deps, symlink scripts, update system prompt.

Run at container startup from each agent's entrypoint.sh.  The agent passes
its workspace modules directory and the path to its system-prompt file
(``AGENTS.md`` for Codex/Gemini, ``CLAUDE.md`` for Claude, etc.).

Bundled modules (shipped inside the ``superpos_agent_core`` package under
``modules/``) are always merged in alongside the workspace modules — see
:func:`superpos_agent_core.module_loader.discover_modules`.  Setup scripts
and ``requirements.txt`` are only run for workspace modules, since the
package directory is typically read-only on a pip-installed core; bundled
modules should declare their Python deps in core's own ``pyproject.toml``.
"""

from __future__ import annotations

import argparse
import logging
import os
import stat
import subprocess
import sys
from pathlib import Path

from .module_loader import (
    bundled_modules_dir,
    discover_modules,
    generate_modules_doc,
)

log = logging.getLogger(__name__)

BEGIN_MARKER = "<!-- MODULES:BEGIN -->"
END_MARKER = "<!-- MODULES:END -->"


def run_setup_scripts(modules_dir: str) -> None:
    """Run each workspace module's setup.sh if present.

    Skips bundled modules — the package directory is not a writable
    install target.  If a bundled module needs build-time setup, ship it
    pre-built.
    """
    for entry in sorted(Path(modules_dir).iterdir()):
        setup = entry / "setup.sh"
        if setup.exists():
            log.info("Running setup.sh for module %s", entry.name)
            setup.chmod(setup.stat().st_mode | 0o111)
            subprocess.run(["bash", str(setup)], check=True, cwd=str(entry))


def install_requirements(modules_dir: str) -> None:
    """Install requirements.txt for each workspace module that has one."""
    for entry in sorted(Path(modules_dir).iterdir()):
        req = entry / "requirements.txt"
        if req.exists():
            log.info("Installing deps for module %s", entry.name)
            subprocess.run(
                [
                    sys.executable, "-m", "pip", "install",
                    "--break-system-packages", "-q", "-r", str(req),
                ],
                check=True,
            )


def update_agents_md(doc: str, agents_md_path: str) -> None:
    """Replace content between MODULES markers in the agent's system-prompt file."""
    if not os.path.exists(agents_md_path):
        log.warning("System-prompt file not found at %s", agents_md_path)
        return

    with open(agents_md_path) as f:
        content = f.read()

    begin = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    if begin == -1 or end == -1:
        log.warning("Module markers not found in %s — skipping update", agents_md_path)
        return

    replacement = (
        f"{BEGIN_MARKER}\n"
        "<!-- Auto-generated by superpos_agent_core.module_setup — do not edit manually -->\n\n"
        f"{doc}\n"
        f"{END_MARKER}"
    )
    new_content = content[:begin] + replacement + content[end + len(END_MARKER):]

    with open(agents_md_path, "w") as f:
        f.write(new_content)

    log.info("Updated %s with module documentation", agents_md_path)


def symlink_module_scripts(modules_dir: str | None, bin_dir: str) -> None:
    """Symlink every module's executable script into ``bin_dir`` (created if missing).

    Walks bundled modules first, then the workspace ``modules_dir`` — so a
    workspace script with the same basename as a bundled one wins.  The
    target file is chmod +x'd so the symlink is callable without further
    setup.
    """
    bin_path = Path(bin_dir)
    bin_path.mkdir(parents=True, exist_ok=True)

    roots: list[Path] = []
    bundled = Path(bundled_modules_dir())
    if bundled.is_dir():
        roots.append(bundled)
    if modules_dir:
        ws = Path(modules_dir)
        if ws.is_dir():
            roots.append(ws)

    for root in roots:
        for module_entry in sorted(root.iterdir()):
            scripts_dir = module_entry / "scripts"
            if not scripts_dir.is_dir():
                continue
            for script in sorted(scripts_dir.iterdir()):
                if not script.is_file():
                    continue
                try:
                    script.chmod(script.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
                except PermissionError:
                    # Bundled scripts on a read-only install — they're
                    # already +x at build time, so a chmod failure here
                    # is non-fatal.
                    log.debug("Could not chmod %s (read-only?); continuing", script)
                # symlink_to stores the literal target string, resolved
                # *relative to the symlink location* — not the cwd.  If
                # the caller passed a relative ``modules_dir`` (e.g.
                # ``.codex/modules``), the script Path is relative too,
                # and the resulting symlink would point at a sibling of
                # ``bin_dir`` that doesn't exist.  Resolve to an absolute
                # path so the link is correct regardless of caller cwd.
                resolved_script = script.resolve()
                target = bin_path / script.name
                if target.is_symlink() or target.exists():
                    target.unlink()
                target.symlink_to(resolved_script)
                log.debug("Linked %s -> %s", target, resolved_script)


def run_setup(
    modules_dir: str,
    agents_md_path: str,
    *,
    bin_dir: str | None = None,
    registry_resolved: dict | None = None,
    skills_dir: str | None = None,
) -> None:
    """Discover modules, run setup scripts, install deps, update system prompt.

    ``bin_dir`` (optional) — if provided, every discovered module's
    ``scripts/`` files are symlinked here.  Set to a directory that's on
    ``$PATH`` so the agent can invoke scripts by name.

    ``registry_resolved`` (optional, Beat 2b) — when the
    ``PLATFORM_REGISTRY_SERVE_SKILLS_MODULES`` flag is ON, pass the parsed
    ``/registry/resolved`` payload here and the registry-served skills +
    modules are overlaid on top of the baked-in set (registry wins on slug
    collision).  When the flag is OFF this argument is ignored entirely —
    the baked-in path below runs exactly as before, which is the
    instant-rollback guarantee.  Pass ``None`` (or a flag-off env) to keep
    today's behaviour.
    """
    if not os.path.isdir(modules_dir):
        log.info(
            "No workspace modules directory at %s — proceeding with bundled modules only",
            modules_dir,
        )

    # Instant-rollback: when the Beat 2b flag is OFF, purge any registry
    # modules a prior flag-ON run materialised into the persistent
    # ``modules_dir`` (plus their PATH symlinks) BEFORE the baked-in
    # discover/symlink/doc steps below — otherwise those steps would still
    # pick them up and the flag-off path would NOT be back to baked-in.
    # Lazy import avoids a circular import (registry_overlay imports here).
    from .registry_overlay import (
        feature_enabled,
        remove_registry_overlay_modules,
    )

    if not feature_enabled():
        rolled_back = remove_registry_overlay_modules(modules_dir, bin_dir=bin_dir)
        if rolled_back:
            log.info(
                "Registry overlay flag OFF: removed %d registry-managed "
                "module(s) for instant rollback: %s",
                len(rolled_back), rolled_back,
            )

    modules = discover_modules(modules_dir if os.path.isdir(modules_dir) else None)
    log.info("Discovered %d module(s): %s", len(modules), [m.name for m in modules])

    if os.path.isdir(modules_dir):
        run_setup_scripts(modules_dir)
        install_requirements(modules_dir)

    if bin_dir:
        symlink_module_scripts(modules_dir, bin_dir)

    # The auto-generated block leads with the superpos-task CLI reference
    # (rendered from the live argparse parser, so it can never drift from the
    # installed flags) followed by the discovered-modules listing.
    from .task_cli_doc import render_task_cli_reference

    doc = render_task_cli_reference() + "\n" + generate_modules_doc(modules)
    update_agents_md(doc, agents_md_path)

    # Beat 2b: overlay registry-served skills + modules on top of baked-in.
    # Imported lazily to avoid a circular import (registry_overlay imports
    # from this module).  ``feature_enabled`` is re-checked inside
    # ``apply_registry_overlay`` — when the flag is OFF this is a no-op and
    # nothing above changed, preserving the baked-in-only path bit-for-bit.
    from .registry_overlay import apply_registry_overlay

    # Modules are overlaid into the workspace modules dir and do NOT need a
    # skills_dir; only the skills half of the overlay does.  So gate the
    # overlay solely on the flag — ``apply_registry_overlay`` skips just the
    # skills portion when ``skills_dir`` is missing and still installs
    # modules.  (Previously this whole call was gated on ``skills_dir``, so a
    # flag-on startup command without a skills dir silently overlaid nothing.)
    if feature_enabled():
        apply_registry_overlay(
            registry_resolved,
            modules_dir=modules_dir,
            skills_dir=skills_dir,
            agents_md_path=agents_md_path,
            bin_dir=bin_dir,
        )


def _fetch_registry_resolved() -> dict | None:
    """Sync fetch of ``/registry/resolved`` for the CLI entrypoint path.

    Mirrors ``sub_agent_sync.fetch_runtime_bundle``'s defensive style:
    returns ``None`` on any transport / status / parse failure so the
    caller falls back entirely to baked-in.  Only called when the Beat 2b
    flag is on and ``SUPERPOS_BASE_URL`` / ``SUPERPOS_API_TOKEN`` are set.
    """
    import httpx

    base_url = os.environ.get("SUPERPOS_BASE_URL", "").rstrip("/")
    token = os.environ.get("SUPERPOS_API_TOKEN", "")
    if not base_url or not token:
        log.warning(
            "Registry overlay flag on but SUPERPOS_BASE_URL/SUPERPOS_API_TOKEN "
            "unset; falling back to baked-in.",
        )
        return None
    try:
        with httpx.Client(
            base_url=base_url, timeout=30.0, follow_redirects=True,
        ) as client:
            resp = client.get(
                "/api/v1/registry/resolved",
                headers={
                    "Accept": "application/json",
                    "Authorization": f"Bearer {token}",
                },
            )
        if resp.status_code != 200:
            log.warning(
                "Registry resolved returned %s; falling back to baked-in.",
                resp.status_code,
            )
            return None
        data = resp.json()
    except Exception as exc:  # noqa: BLE001 — degrade to baked-in on any error
        log.warning("Registry resolved fetch failed (%s); baked-in only.", exc)
        return None
    payload = data.get("data", data) if isinstance(data, dict) else None
    return payload if isinstance(payload, dict) else None


def main() -> None:
    """CLI entry point invoked from entrypoint.sh."""
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    parser = argparse.ArgumentParser(description="Superpos agent module setup")
    parser.add_argument(
        "--modules-dir", required=True,
        help="Path to the agent's modules directory (e.g. /workspace/.gemini/modules)",
    )
    parser.add_argument(
        "--agents-md", required=True,
        help="Path to the agent's system-prompt file (e.g. /workspace/AGENTS.md)",
    )
    parser.add_argument(
        "--bin-dir",
        help=(
            "Optional directory to symlink every module's scripts into. "
            "Add this directory to PATH so the agent can invoke them by name."
        ),
    )
    parser.add_argument(
        "--skills-dir",
        help=(
            "Optional skills directory (e.g. /workspace/.claude/skills). "
            "Required for the Beat 2b registry overlay to write skills; "
            "registry modules are overlaid even without it."
        ),
    )
    args = parser.parse_args()

    # Beat 2b: only touch the registry when the flag is on (default ON; an
    # explicit-false flag → zero registry calls, identical to baked-in path).
    from .registry_overlay import feature_enabled

    # Fetch the resolved set whenever the flag is on — NOT conditioned on
    # ``--skills-dir``.  Modules are overlaid regardless of a skills dir, so
    # gating the fetch on ``--skills-dir`` meant a flag-on rollout for a
    # startup command without that flag never fetched and only rendered
    # baked-in modules.  ``apply_registry_overlay`` skips only the skills
    # half when no skills dir is available.
    registry_resolved = None
    if feature_enabled():
        registry_resolved = _fetch_registry_resolved()

    run_setup(
        args.modules_dir,
        args.agents_md,
        bin_dir=args.bin_dir,
        registry_resolved=registry_resolved,
        skills_dir=args.skills_dir,
    )


if __name__ == "__main__":
    main()
